### ISSUE TITLE
Missing license.txt file

### ISSUE THREAD

**Issue by davedarko** [adafruit/Adafruit-Feather-M0-Basic-Proto-PCB#1]
the ReadMe says "check license.txt for more information", but there is no such file (as well as on the data logger). I'm wondering if I can use the design for a starting point to make an ATSAMD21J18 for the hackaday.io prize.

Sorry for the hassle, I'm just starting to research.

**Comment by ladyada** [comment]
hiya - it is "Creative Commons Attribution, Share-Alike license" so go ahead as long as you release your changes under the same license :) good luck!!!!

**Comment by davedarko** [comment]
Hey, thanks! That's actually what is in the description as well, I thought there is a longer Version, but google leads me to this, https://creativecommons.org/licenses/by-sa/2.5/ - so I'll take that, thanks!
